/* East Window Studio — small dependency-free WebGL renderer. */
'use strict';
window.Nest3D = (() => {
  const add=(a,b)=>a.map((v,i)=>v+b[i]), sub=(a,b)=>a.map((v,i)=>v-b[i]), mul=(a,s)=>a.map(v=>v*s), dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);
  const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]], norm=a=>mul(a,1/(Math.hypot(...a)||1));
  const I=()=>[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];
  function mm(a,b){const r=new Array(16).fill(0);for(let c=0;c<4;c++)for(let y=0;y<4;y++)for(let k=0;k<4;k++)r[c*4+y]+=a[k*4+y]*b[c*4+k];return r;}
  const T=(x=0,y=0,z=0)=>[1,0,0,0,0,1,0,0,0,0,1,0,x,y,z,1];
  const S=(x=1,y=x,z=x)=>[x,0,0,0,0,y,0,0,0,0,z,0,0,0,0,1];
  const RX=a=>[1,0,0,0,0,Math.cos(a),Math.sin(a),0,0,-Math.sin(a),Math.cos(a),0,0,0,0,1];
  const RY=a=>[Math.cos(a),0,-Math.sin(a),0,0,1,0,0,Math.sin(a),0,Math.cos(a),0,0,0,0,1];
  const RZ=a=>[Math.cos(a),Math.sin(a),0,0,-Math.sin(a),Math.cos(a),0,0,0,0,1,0,0,0,0,1];
  const transform=(m,p,w=1)=>[m[0]*p[0]+m[4]*p[1]+m[8]*p[2]+m[12]*w,m[1]*p[0]+m[5]*p[1]+m[9]*p[2]+m[13]*w,m[2]*p[0]+m[6]*p[1]+m[10]*p[2]+m[14]*w];
  function look(eye,target,up=[0,1,0]){const z=norm(sub(eye,target)),x=norm(cross(up,z)),y=cross(z,x);return[x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1];}
  const ortho=(l,r,b,t,n,f)=>[2/(r-l),0,0,0,0,2/(t-b),0,0,0,0,-2/(f-n),0,-(r+l)/(r-l),-(t+b)/(t-b),-(f+n)/(f-n),1];
  const color=s=>{if(Array.isArray(s))return s;let v=parseInt(s.replace('#',''),16);return[(v>>16&255)/255,(v>>8&255)/255,(v&255)/255,1];};
  function tri(arr,a,b,c,na,nb,nc,ua=[0,0],ub=[1,0],uc=[1,1]){for(const [p,n,u] of [[a,na,ua],[b,nb,ub],[c,nc,uc]])arr.push(...p,...n,...u);}
  function box(w,h,d,r=0.02){r=Math.min(r,w/2-.0001,h/2-.0001,d/2-.0001);r=Math.max(0,r);const a=[],size=[w/2,h/2,d/2],steps=r>0?5:1;
    for(let axis=0;axis<3;axis++)for(const sign of [-1,1]){const u=(axis+1)%3,v=(axis+2)%3;
      function pt(i,j){const q=[0,0,0];q[axis]=sign*size[axis];const at=(k,s)=>r?[-s,-s+r*.32,-s+r,s-r,s-r*.32,s][k]:(k*2-1)*s;q[u]=at(i,size[u]);q[v]=at(j,size[v]);const c=q.map((x,k)=>Math.max(-size[k]+r,Math.min(size[k]-r,x)));let n=r?norm(sub(q,c)):[0,0,0];if(!r)n[axis]=sign;return [add(c,mul(n,r)),n,[i/steps,j/steps]];}
      for(let i=0;i<steps;i++)for(let j=0;j<steps;j++){const A=pt(i,j),B=pt(i+1,j),C=pt(i+1,j+1),D=pt(i,j+1);tri(a,A[0],B[0],C[0],A[1],B[1],C[1],A[2],B[2],C[2]);tri(a,A[0],C[0],D[0],A[1],C[1],D[1],A[2],C[2],D[2]);}}
    return a;}
  function sphere(rx,ry=rx,rz=rx,seg=14,rings=9){const a=[];function p(i,j){let t=j/rings*Math.PI,f=i/seg*Math.PI*2;const q=[Math.sin(t)*Math.cos(f),Math.cos(t),Math.sin(t)*Math.sin(f)];return[[q[0]*rx,q[1]*ry,q[2]*rz],norm([q[0]/rx,q[1]/ry,q[2]/rz]),[i/seg,j/rings]];}
    for(let i=0;i<seg;i++)for(let j=0;j<rings;j++){const A=p(i,j),B=p(i+1,j),C=p(i+1,j+1),D=p(i,j+1);tri(a,A[0],B[0],C[0],A[1],B[1],C[1],A[2],B[2],C[2]);tri(a,A[0],C[0],D[0],A[1],C[1],D[1],A[2],C[2],D[2]);}return a;}
  function lathe(profile,segments=24){const a=[];for(let j=0;j<profile.length-1;j++){let [r1,y1]=profile[j],[r2,y2]=profile[j+1];const ny=r1-r2,nr=y2-y1;
    function p(r,y,i){const t=i/segments*Math.PI*2;return [[Math.cos(t)*r,y,Math.sin(t)*r],norm([nr*Math.cos(t),ny,nr*Math.sin(t)]),[i/segments,y]];}
    for(let i=0;i<segments;i++){let A=p(r1,y1,i),B=p(r1,y1,i+1),C=p(r2,y2,i+1),D=p(r2,y2,i);tri(a,A[0],B[0],C[0],A[1],B[1],C[1],A[2],B[2],C[2]);tri(a,A[0],C[0],D[0],A[1],C[1],D[1],A[2],C[2],D[2]);}}return a;}
  const cylinder=(rt,rb,h,n=20)=>lathe([[0,-h/2],[rb,-h/2],[rt,h/2],[0,h/2]],n);
  function plane(w,h,curvature=0){const a=[],nx=curvature?6:1,ny=curvature?10:1;function p(i,j){const x=(i/nx-.5)*w,y=j/ny*h;return [[x,y,curvature*(Math.sin(j/ny*Math.PI)*.4+Math.abs(x/w)*.4)],norm([-Math.sign(x)*curvature/w,0,1]),[i/nx,1-j/ny]];}
    for(let i=0;i<nx;i++)for(let j=0;j<ny;j++){let A=p(i,j),B=p(i+1,j),C=p(i+1,j+1),D=p(i,j+1);tri(a,A[0],B[0],C[0],A[1],B[1],C[1],A[2],B[2],C[2]);tri(a,A[0],C[0],D[0],A[1],C[1],D[1],A[2],C[2],D[2]);}return a;}
  class Builder{
    constructor(){this.buckets={};}
    put(g,c='#ffffff',m=I(),opts={}){const key=[opts.tex||'',opts.glow||0,opts.alpha||1,opts.shadow!==false].join('|');let b=this.buckets[key];if(!b)b=this.buckets[key]={data:[],tex:opts.tex||'',glow:opts.glow||0,alpha:opts.alpha||1,shadow:opts.shadow!==false};const col=color(c);
      for(let i=0;i<g.length;i+=8){const p=transform(m,g.slice(i,i+3)),n=norm(transform(m,g.slice(i+3,i+6),0));b.data.push(...p,...n,g[i+6],g[i+7],...col);}return this;}
    box(w,h,d,c,x=0,y=0,z=0,r=.025,rot=0,opts={}){return this.put(box(w,h,d,r),c,mm(T(x,y,z),RY(rot)),opts);}
    ball(rx,ry,rz,c,x=0,y=0,z=0,opts={}){return this.put(sphere(rx,ry,rz),c,T(x,y,z),opts);}
    cyl(rt,rb,h,c,x=0,y=0,z=0,opts={}){return this.put(cylinder(rt,rb,h),c,T(x,y,z),opts);}
    rod(a,b,r,c){const v=sub(b,a),Y=norm(v),X=norm(cross(Math.abs(Y[1])>.96?[1,0,0]:[0,1,0],Y)),Z=cross(X,Y),o=mul(add(a,b),.5),mat=[...X,0,...Y,0,...Z,0,...o,1];return this.put(cylinder(r,r,Math.hypot(...v),8),c,mat);}
    flat(w,h,tex,x,y,z,rotX=0,rotY=0,c='#ffffff',opts={}){return this.put(plane(w,h),c,mm(T(x,y,z),mm(RY(rotY),RX(rotX))),{...opts,tex});}
    finish(){return Object.values(this.buckets);}
  }
  const vertex=`attribute vec3 aPos;attribute vec3 aNormal;attribute vec2 aUV;attribute vec4 aColor;uniform mat4 uVP;uniform mat4 uModel;uniform mat4 uLightVP;varying vec3 vN;varying vec3 vWorld;varying vec2 vUV;varying vec4 vColor;varying vec4 vShadow;void main(){vec4 w=uModel*vec4(aPos,1.);vWorld=w.xyz;vN=normalize(mat3(uModel)*aNormal);vUV=aUV;vColor=aColor;vShadow=uLightVP*w;gl_Position=uVP*w;}`;
  const fragment=`precision highp float;varying vec3 vN;varying vec3 vWorld;varying vec2 vUV;varying vec4 vColor;varying vec4 vShadow;uniform sampler2D uTex;uniform sampler2D uShadow;uniform float uHasTex;uniform float uGlow;uniform float uAlpha;uniform float uShadowOn;uniform float uNight;uniform int uPass;uniform vec3 uId;uniform vec3 uSun;void main(){vec4 t=mix(vec4(1.),texture2D(uTex,vUV),uHasTex);if(t.a<.05)discard;if(uPass==1){gl_FragColor=vec4(1.);return;}if(uPass==2){gl_FragColor=vec4(uId,1.);return;}vec3 n=normalize(vN);float sun=max(dot(n,uSun),0.);float hemi=.70+.09*n.y;vec3 sc=vShadow.xyz/vShadow.w*.5+.5;float shade=0.;if(uShadowOn>.5&&sc.x>0.&&sc.x<1.&&sc.y>0.&&sc.y<1.&&sc.z<1.){float bias=max(.0014*(1.-sun),.00055);for(int x=-1;x<=1;x++)for(int y=-1;y<=1;y++){float d=texture2D(uShadow,sc.xy+vec2(float(x),float(y))/1536.).r;shade+=sc.z-bias>d?1.:0.;}shade/=9.;}float lit=hemi+sun*.34*(1.-shade*.8);lit-=shade*.055;vec3 base=vColor.rgb*t.rgb;vec3 warm=mix(vec3(1.035,1.01,.96),vec3(1.12,.94,.72),uNight);vec3 c=base*lit*warm;c=mix(c,base,uGlow);c=mix(c,c*vec3(.78,.83,.88),uNight*.2);gl_FragColor=vec4(c,t.a*vColor.a*uAlpha);}`;
  class Renderer{
    constructor(canvas,textures={}){this.canvas=canvas;this.gl=canvas.getContext('webgl',{antialias:true,alpha:false,preserveDrawingBuffer:true});if(!this.gl)throw new Error('WebGL 不可用。请使用开启硬件加速的现代浏览器。');const g=this.gl;this.textures={};this.items=[];this.arch=[];this.azimuth=-.60;this.elevation=.72;this.zoom=1;this.target=[0,.65,0];this.night=0;this.top=false;this.walls=true;this.ceiling=false;
      function compile(type,src){const s=g.createShader(type);g.shaderSource(s,src);g.compileShader(s);if(!g.getShaderParameter(s,g.COMPILE_STATUS))throw new Error(g.getShaderInfoLog(s));return s;}
      this.program=g.createProgram();g.attachShader(this.program,compile(g.VERTEX_SHADER,vertex));g.attachShader(this.program,compile(g.FRAGMENT_SHADER,fragment));g.linkProgram(this.program);if(!g.getProgramParameter(this.program,g.LINK_STATUS))throw new Error(g.getProgramInfoLog(this.program));g.useProgram(this.program);this.attr={};for(const n of ['aPos','aNormal','aUV','aColor'])this.attr[n]=g.getAttribLocation(this.program,n);this.uni={};for(const n of ['uVP','uModel','uLightVP','uTex','uShadow','uHasTex','uGlow','uAlpha','uShadowOn','uNight','uPass','uId','uSun'])this.uni[n]=g.getUniformLocation(this.program,n);
      for(const [k,v]of Object.entries(textures))this.addTexture(k,v);this.addTexture('__white',Object.assign(document.createElement('canvas'),{width:2,height:2}));
      this.sun=norm([5,9,4]);this.lightVP=mm(ortho(-7,7,-7,7,.1,35),look(mul(this.sun,18),[0,0,0]));this.shadowExt=g.getExtension('WEBGL_depth_texture');if(this.shadowExt)this.makeShadow();g.enable(g.DEPTH_TEST);g.disable(g.CULL_FACE);g.pixelStorei(g.UNPACK_FLIP_Y_WEBGL,false);this.resize();}
    addTexture(name,canvas){const g=this.gl,t=g.createTexture();g.bindTexture(g.TEXTURE_2D,t);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,g.RGBA,g.UNSIGNED_BYTE,canvas);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);this.textures[name]=t;}
    makeShadow(){const g=this.gl;this.shadowFB=g.createFramebuffer();g.bindFramebuffer(g.FRAMEBUFFER,this.shadowFB);this.shadowTex=g.createTexture();g.bindTexture(g.TEXTURE_2D,this.shadowTex);g.texImage2D(g.TEXTURE_2D,0,g.DEPTH_COMPONENT,1536,1536,0,g.DEPTH_COMPONENT,g.UNSIGNED_INT,null);for(const p of [g.TEXTURE_MIN_FILTER,g.TEXTURE_MAG_FILTER])g.texParameteri(g.TEXTURE_2D,p,g.NEAREST);for(const p of [g.TEXTURE_WRAP_S,g.TEXTURE_WRAP_T])g.texParameteri(g.TEXTURE_2D,p,g.CLAMP_TO_EDGE);g.framebufferTexture2D(g.FRAMEBUFFER,g.DEPTH_ATTACHMENT,g.TEXTURE_2D,this.shadowTex,0);this.shadowColor=g.createTexture();g.bindTexture(g.TEXTURE_2D,this.shadowColor);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,1536,1536,0,g.RGBA,g.UNSIGNED_BYTE,null);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.NEAREST);g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT0,g.TEXTURE_2D,this.shadowColor,0);if(g.checkFramebufferStatus(g.FRAMEBUFFER)!==g.FRAMEBUFFER_COMPLETE)this.shadowExt=null;g.bindFramebuffer(g.FRAMEBUFFER,null);}
    upload(parts){return parts.map(p=>{const g=this.gl,b=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,new Float32Array(p.data),g.STATIC_DRAW);return {...p,buffer:b,count:p.data.length/12,data:null};});}
    dispose(parts){for(const p of parts||[])this.gl.deleteBuffer(p.buffer);}
    resize(){const r=this.canvas.getBoundingClientRect(),d=Math.min(window.devicePixelRatio||1,1.7);this.width=r.width;this.height=r.height;this.canvas.width=Math.max(1,Math.round(r.width*d));this.canvas.height=Math.max(1,Math.round(r.height*d));this.camera();this.pickDirty=true;}
    camera(){const az=this.azimuth,el=this.top?Math.PI/2-.001:this.elevation,dir=[Math.sin(az)*Math.cos(el),Math.sin(el),Math.cos(az)*Math.cos(el)];this.eye=add(this.target,mul(dir,15));this.forward=mul(dir,-1);this.right=norm(cross(this.forward,[0,1,0]));this.up=cross(this.right,this.forward);const ar=this.width/Math.max(1,this.height);this.half=Math.max(5.2,5.1/ar)/this.zoom;this.VP=mm(ortho(-this.half*ar,this.half*ar,-this.half,this.half,.1,50),look(this.eye,this.target));}
    point(x,y,planeY=0){const nx=x/this.width*2-1,ny=1-y/this.height*2,origin=add(this.eye,add(mul(this.right,nx*this.half*this.width/this.height),mul(this.up,ny*this.half))),t=(planeY-origin[1])/this.forward[1];return add(origin,mul(this.forward,t));}
    project(p){const q=transform(this.VP,p);return[(q[0]*.5+.5)*this.width,(.5-q[1]*.5)*this.height,q[2]];}
    matrix(o,map,visited=new Set()){if(visited.has(o.id))return I();visited.add(o.id);let m=mm(T(o.x,o.y||0,o.z),RY(o.r||0));if(o.parent&&map.has(o.parent))m=mm(this.matrix(map.get(o.parent),map,visited),m);return m;}
    setScene(arch,items){this.arch=arch;this.items=items;this.map=new Map(items.map(o=>[o.id,o]));}
    render(pass=0){const g=this.gl,U=this.uni;g.useProgram(this.program);g.uniform1i(U.uPass,pass);g.uniformMatrix4fv(U.uVP,false,pass===1?this.lightVP:this.VP);g.uniformMatrix4fv(U.uLightVP,false,this.lightVP);g.uniform1i(U.uTex,0);g.uniform1i(U.uShadow,1);g.uniform3fv(U.uSun,this.sun);g.uniform1f(U.uNight,this.night);g.uniform1f(U.uShadowOn,this.shadowExt&&pass===0?1:0);g.activeTexture(g.TEXTURE1);g.bindTexture(g.TEXTURE_2D,pass===1?null:this.shadowTex||null);g.activeTexture(g.TEXTURE0);
      for(const o of [...this.arch,...this.items]){if(o.helper&&pass!==0||o.visible===false||o.parent&&this.map.get(o.parent)?.visible===false||o.ceiling&&!this.ceiling||o.wall&&(!this.walls||this.top)||o.noTop&&this.top)continue;const m=o.model||this.matrix(o,this.map);g.uniformMatrix4fv(U.uModel,false,m);let id=o.pickId||0;g.uniform3fv(U.uId,[(id&255)/255,((id>>8)&255)/255,((id>>16)&255)/255]);
        for(const p of o.parts){if(pass===1&&!p.shadow)continue;g.bindBuffer(g.ARRAY_BUFFER,p.buffer);for(const[n,k,size]of[['aPos',0,3],['aNormal',3,3],['aUV',6,2],['aColor',8,4]]){g.enableVertexAttribArray(this.attr[n]);g.vertexAttribPointer(this.attr[n],size,g.FLOAT,false,48,k*4);}g.bindTexture(g.TEXTURE_2D,this.textures[p.tex]||this.textures.__white);g.uniform1f(U.uHasTex,p.tex?1:0);g.uniform1f(U.uGlow,p.glow);g.uniform1f(U.uAlpha,p.alpha);if(p.alpha<1&&pass===0){g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);g.depthMask(false);}else{g.disable(g.BLEND);g.depthMask(true);}g.drawArrays(g.TRIANGLES,0,p.count);}}
      g.depthMask(true);g.disable(g.BLEND);}
    frame(shadow=true){this.camera();const g=this.gl;if(this.shadowExt&&shadow){g.bindFramebuffer(g.FRAMEBUFFER,this.shadowFB);g.viewport(0,0,1536,1536);g.clearColor(1,1,1,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);this.render(1);}g.bindFramebuffer(g.FRAMEBUFFER,null);g.viewport(0,0,this.canvas.width,this.canvas.height);g.clearColor(...(this.night>.5?[.85,.82,.77,1]:[.943,.929,.897,1]));g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);this.render(0);}
    pick(x,y){const g=this.gl;g.bindFramebuffer(g.FRAMEBUFFER,null);g.viewport(0,0,this.canvas.width,this.canvas.height);g.clearColor(0,0,0,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);this.render(2);const out=new Uint8Array(4),dx=Math.min(this.canvas.width-1,Math.max(0,Math.floor(x/this.width*this.canvas.width))),dy=Math.min(this.canvas.height-1,Math.max(0,Math.floor((1-y/this.height)*this.canvas.height)));g.readPixels(dx,dy,1,1,g.RGBA,g.UNSIGNED_BYTE,out);const id=out[0]+(out[1]<<8)+(out[2]<<16);this.frame(false);return this.items.find(o=>o.pickId===id)||null;}
  }
  return {Renderer,Builder,box,sphere,cylinder,lathe,plane,mm,I,T,S,RX,RY,RZ,transform,add,sub,mul,norm,cross,color};
})();
